#!/usr/bin/with-contenv bash

# check/set multicast
if [ ! -e /config/updated ]; then
    ip link add dummy0 type dummy >/dev/null
    if [ $? -eq 0 ]; then
        echo "Running in privileged mode, setting multicast variables."
	ip link set eth0 multicast on
	iptables -I INPUT -d 224.0.0.0/4 -j ACCEPT
	iptables -I FORWARD -d 224.0.0.0/4 -j ACCEPT
	iptables -I INPUT -d 224.0.0.251/4 -j ACCEPT
	iptables -I FORWARD -d 224.0.0.251/4 -j ACCEPT
	ip route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0
	touch /config/updated
    else
        echo "You need to execute this container in privileged mode at least once!"
    fi
else
    echo "Multicast variables have been set, you can disable privileged mode now."
fi

# fetch site
if [ ! -d /config/www/Phlex/.git ]; then
    echo "No repo found, pulling."
	git clone https://github.com/d8ahazard/Phlex /config/www/Phlex
fi

echo "Updating Phlex."
cd /config/www/Phlex
git pull

# permissions
chown -R abc:abc /config/www
chmod -R 777 /config
	

